### ISSUE TITLE
RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified on Android 14

### ISSUE THREAD

**Issue by davepaiva** [SudoPlz/sp-react-native-in-app-updates#173]
I am aware that this is a duplicate of https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/156
but I tried updating the library to `1.4.0` and added this fix https://stackoverflow.com/questions/75600848/duplicate-class-com-google-android-play-core-appupdate-appupdateinfo-found-in-mo/76043161#76043161 because I was getting duplicate class errors

but the problem persists

crash stack trace:

```
308  7212-7584  AndroidRuntime          pid-7212                             E  FATAL EXCEPTION: create_react_context
                                                                                                    Process: com.****, PID: 7212
                                                                                                    java.lang.SecurityException: com.****: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3087)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3054)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2996)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1860)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1796)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1784)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:765)
                                                                                                    	at com.google.android.play.core.listener.b.b(Unknown Source:27)
                                                                                                    	at com.google.android.play.core.listener.b.f(Unknown Source:21)
                                                                                                    	at com.google.android.play.core.appupdate.d.registerListener(Unknown Source:3)
                                                                                                    	at com.sudoplz.rninappupdates.SpReactNativeInAppUpdatesModule.<init>(SpReactNativeInAppUpdatesModule.java:50)
                                                                                                    	at com.sudoplz.rninappupdates.SpReactNativeInAppUpdatesPackage.createNativeModules(SpReactNativeInAppUpdatesPackage.java:19)
                                                                                                    	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:43)
                                                                                                    	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
                                                                                                    	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1458)
                                                                                                    	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1429)
                                                                                                    	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1331)
                                                                                                    	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1101)
                                                                                                    	at com.facebook.react.ReactInstanceManager.$r8$lambda$AwGS8CysOZmWJw3kRVARHQvw9Ew(Unknown Source:0)
                                                                                                    	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda5.run(Unknown Source:4)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:14845)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2570)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2985)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1387)
                                                                                                    	at android.os.Binder.execTransact(Binder.java:1299)
 ```

**Comment by SudoPlz** [comment]
Are you sure you're on core app `2.1.0 `?

Can you double check what core app version is actually used?

**Comment by davepaiva** [comment]
okay identified the issue :
the fix that was described in the StackOverflow answer:
```
implementation (project(':sp-react-native-in-app-updates')) 
{
  exclude group: "com.google.android.play", module: "app-update"
  exclude group: "com.google.android.play", module: "core"
}
```
was probably ignoring the fix of this lib's latest version.
I fixed the duplicate classes issue by updating one of lib (in my case - https://github.com/MinaSamir11/react-native-in-app-review, the update of which uses the new split packages implementation) that was causing the duplicate classes error.

The issue was resolved by updating both these libs in my case
Thanks for your time @SudoPlz

**Comment by SudoPlz** [comment]
Thanks for the response @davepaiva I'm happy you figured it out.

**Comment by KrushnaNaghate** [comment]
@davepaiva hi can I get a clear step where to add this line of code, also I have a similar issue, so is this solution you provided going to work? 

`          Fatal Exception: java.lang.SecurityException: com.litescan.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
       at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
       at android.os.Parcel.createException(Parcel.java:3041)
       at android.os.Parcel.readException(Parcel.java:3024)
       at android.os.Parcel.readException(Parcel.java:2966)
       at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:5684)
       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1852)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1792)
       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1780)
       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
       at com.google.android.play.core.appupdate.internal.zzl.zze(com.google.android.play:app-update@@2.0.1:4)
       at com.google.android.play.core.appupdate.internal.zzl.zzb(com.google.android.play:app-update@@2.0.1:4)
       at com.google.android.play.core.appupdate.zzg.registerListener(com.google.android.play:app-update@@2.0.1:1)
       at com.sudoplz.rninappupdates.SpReactNativeInAppUpdatesModule.<init>(SpReactNativeInAppUpdatesModule.java:50)
       at com.sudoplz.rninappupdates.SpReactNativeInAppUpdatesPackage.createNativeModules(SpReactNativeInAppUpdatesPackage.java:19)
       at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
       at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
       at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1467)
       at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1438)
       at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1340)
       at com.facebook.react.ReactInstanceManager.-$$Nest$mcreateReactContext()
       at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1111)
       at java.lang.Thread.run(Thread.java:1012)
        `
