### ISSUE TITLE
Getting warning in play console (Update the Play Core Library in your app to the latest version (1.7.2 or above).)

### ISSUE THREAD

**Issue by amit12239** [SudoPlz/sp-react-native-in-app-updates#51]
Critical issues have been reported with the following SDK versions:
com.google.android.play:core:1.7.1
What the SDK developer told us:
Your app contains a vulnerability that can lead to an attacker writing data to your app's internal storage. This is because your app is using an old version of the Play Core Library. Update the Play Core Library in your app to the latest version (1.7.2 or above).

**Comment by jtwilz2021** [comment]
Hi I'm getting these errors when trying to publish app can someone please help. 

StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Ljava/lang/invoke/MethodHandles$Lookup;-><init>(Ljava/lang/Class;I)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:407)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredConstructorInternal(Native Method)
	at java.lang.Class.getConstructor0(Class.java:2329)
	at java.lang.Class.getDeclaredConstructor(Class.java:2170)
	at bitter.jnibridge.JNIBridge$a.<init>(Unknown Source:25)
	at bitter.jnibridge.JNIBridge.newInterfaceProxy(Unknown Source:8)
	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:83)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:237)
	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)

**Comment by SudoPlz** [comment]
[Check this out](https://github.com/SudoPlz/sp-react-native-in-app-updates/issues/25#issuecomment-847220449)

You should use another play core library.
