### ISSUE TITLE
Binder has died

### ISSUE THREAD

**Issue by tsachit** [SudoPlz/sp-react-native-in-app-updates#82]
Any idea what this is or how does this happen?

```
Error: sp-react-native-in-app-updates checkNeedsUpdate error: Error: android.os.RemoteException: AppUpdateService : Binder has died.
  at anonymous(index.android.bundle:4:27)
  at anonymous(index.android.bundle:1:1)
  at res(node_modules/promise/setimmediate/es6-extensions.js:76:16)
  at Promise(node_modules/promise/setimmediate/core.js:56:11)
  at apply(native)
  at <global>(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:212:80)
  at <global>(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:489:3)
  at _callTimer(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:86:3)
  at clearReactNativeMicrotask(node_modules/react-native/Libraries/Core/Timers/JSTimers.js:335:19)
  at MessageQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:241:3)
  at constructor(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:60:19)
  at processCallbacks(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:224:17)
  at flushedQueue(index.android.bundle:423:3)
  at invokeCallbackAndReturnFlushedQueue(index.android.bundle:390:3)
```

**Comment by parth-koshta** [comment]
Hey @tsachit 
I'm also seeing this error, were you able to find out a fix?

**Comment by tsachit** [comment]
> Hey @tsachit I'm also seeing this error, were you able to find out a fix?

Not yet, my guess is the process died while calling `checkNeedsUpdate` method. Not sure how do I fix that.

**Comment by NishantZet** [comment]
Hey @tsachit ,
Did you got anything which can fix this ?

**Comment by Jmzp** [comment]
Any way to fix it? I have the same error

**Comment by priyanshi-zepto** [comment]
any solution here?
